[workspace]
resolver = "3"
members = ["pipecat_rs"]


[workspace.dependencies]
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1.39.0", features = ["full"] }
async-trait = "0.1.87"
tokio-tungstenite = "0.21"
url = "2"
serde_json = "1.0"
tokio-util = "0.7"
