[package]
name = "pipecat-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.39.0", features = ["full"] }
async-trait = "0.1.83"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
glob = "0.3"
thiserror = "1.0"